function [datetime_flow, flowrate] = importFlowCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [DATETIME_FLOW, FLOWRATE] = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [DATETIME_FLOW, FLOWRATE] = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [datetime_flow, flowrate] = importfile("C:\Users\jacob\Documents\New folder (5)\Masking\221104 - Sensitivity and masking tests with Kickr\41J1\New folder\2022-11-04_10h09m59s.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Nov-2022 17:37:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["datetime_flow", "Var2", "Var3", "Var4", "flowrate", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"];
opts.SelectedVariableNames = ["datetime_flow", "flowrate"];
opts.VariableTypes = ["datetime", "string", "string", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "datetime_flow", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
datetime_flow = tbl.datetime_flow;
flowrate = tbl.flowrate;
end