function [label, timing] = importDefaultsFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [LABEL, TIMING] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [LABEL, TIMING] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [label, timing] = importfile("C:\Users\jacob\Documents\timeTesting\230413 - 44I1 - Run 1 - Stock PBS - Dev\230413_133247_44I1_PBS\defaultData.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Apr-2023 12:29:11

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["label", "timing"];
opts.VariableTypes = ["string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "label", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "label", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
label = tbl.label;
timing = tbl.timing;
end