function assayParameters = salvusImportAssayParams(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ASSAYPARAMETERS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  ASSAYPARAMETERS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  assayParameters = importfile("T:\salvusData\concalgoissue 20230614\230614_052632_4AA5_PBS\assayParameters.log", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 14-Jun-2023 20:46:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Analyte", "PBS"];
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Analyte", "PBS"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Analyte", "PBS"], "EmptyFieldRule", "auto");

% Import the data
assayParameters = readmatrix(filename, opts);

end